apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80        # external port
    targetPort: 4499  # container port
